layout_spectrum: 0.2470734
typography_spectrum: 0.3865858
color:
  saturation: 0.01467697
  lightness: 0.2998896
  brandStrength: 0.4960105
  rhythmicContrast: 0.3163724
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: Leeds
